[project]
name = "gcs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-cloud-storage>=3.1.0",
    "python-dotenv>=1.1.0",
]
